# Generated by Django 2.1.7 on 2019-02-27 15:12

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190227_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedSchoolInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities', multiselectfield.db.fields.MultiSelectField(choices=[('carol', 'Creche'), ('interhousesports', 'Interhouse Sports'), ('culturalday', 'Cultural Day'), ('dance', 'Dance'), ('spellingbees', 'Spelling Bees'), ('debate', 'Debate'), ('quiz', 'Quiz'), ('swimming', 'Swimming'), ('karate', 'Karate'), ('costumeday', 'Costume Day')], default='debate', max_length=92)),
                ('clubs', multiselectfield.db.fields.MultiSelectField(choices=[('bscout', 'Boys Scout'), ('gguide', 'Girls Guide'), ('frsc', 'FRSC Club'), ('music', 'Music Club'), ('drama', 'Drama Club'), ('debate', 'Debate Club'), ('press', 'Press Club'), ('jets', 'JETS Club'), ('rcross', 'Red Cross'), ('artscraft', 'Arts-Craft Club')], default='debate', max_length=65)),
                ('facilities', multiselectfield.db.fields.MultiSelectField(choices=[('sickbay', 'Sickbay'), ('multipurposehall', 'Multipurpose Hall'), ('sciencelab', 'Science Lab'), ('busservice', 'Bus Service'), ('library', 'Library'), ('playground', 'Playground'), ('sportscomplex', 'Sports Complex'), ('ictcenter', 'ICT Center'), ('artstudio', 'Art Studio'), ('elibrary', 'E-Library'), ('swimmingpool', 'Swimming Pool'), ('orchard', 'Orchard'), ('farmhouse', 'Farmhouse'), ('specialneeds', 'Special Needs Care'), ('musicstudio', 'Music Studio'), ('stem', 'STEM'), ('homemanagementlab', 'Home Management Lab'), ('languagestudio', 'Language Studio')], default='playground', max_length=202)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
        ),
        migrations.AlterField(
            model_name='basicschoolinfo',
            name='approved_exams',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ncce', 'National Common Entrance Examinations'), ('scce', 'State Common Entrance Examinatins'), ('waec', 'West African Examination Council Exams'), ('neco', 'National Examinations Council Exams'), ('jwaec', 'Junior West African Examination Council Exams'), ('jneco', 'Junior National Examinations Council Exams'), ('toefl', 'TOEFL Exams'), ('ielts', 'IELTS Exams'), ('alevel', 'A-Levels Exams'), ('igcse', 'IGCSE Exams')], default='ncce', max_length=56),
        ),
        migrations.AlterField(
            model_name='basicschoolinfo',
            name='gender',
            field=models.CharField(choices=[('m', 'Male Only'), ('f', 'Female Only'), ('mx', 'Mixed')], default='mixed', max_length=2),
        ),
        migrations.AlterField(
            model_name='basicschoolinfo',
            name='school_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('c', 'Creche'), ('n', 'Nursery'), ('p', 'Primary'), ('s', 'Secondary'), ('al', 'A-Levels')], default='n', max_length=10),
        ),
    ]
