# Generated by Django 2.1.7 on 2019-02-27 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20190227_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolsconnbaseuser',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='schoolsconnbaseuser',
            name='lname',
        ),
    ]
