# Generated by Django 2.1.3 on 2019-04-07 02:46

from django.db import migrations, models
import school.models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=school.models.user_directory_path),
        ),
    ]
