# Generated by Django 2.1.7 on 2019-02-27 23:44

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20190228_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicschoolinfo',
            name='school_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('c', 'Creche'), ('n', 'Nursery'), ('p', 'Primary'), ('s', 'Secondary'), ('al', 'A-Levels')], default='c, n', max_length=10),
        ),
    ]
