# Generated by Django 2.1.7 on 2019-04-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20190407_0355'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='desc_multiple',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_multiple',
            field=models.FileField(blank=True, upload_to='schools/multiple/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, upload_to='schools/'),
        ),
    ]
