# Generated by Django 2.1.7 on 2019-03-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20190228_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicschoolinfo',
            name='gender',
            field=models.CharField(choices=[('m', 'Male Only'), ('f', 'Female Only'), ('mx', 'Mixed')], default='mx', max_length=2),
        ),
    ]
