# Generated by Django 2.1.7 on 2019-04-08 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20190408_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmultiple',
            name='doc_multiple',
            field=models.ImageField(blank=True, upload_to='schools/multiple/'),
        ),
    ]
