# Generated by Django 2.1.7 on 2019-03-27 08:42

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_auto_20190311_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='activities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('carol', 'Creche'), ('interhousesports', 'Interhouse Sports'), ('culturalday', 'Cultural Day'), ('dance', 'Dance'), ('spellingbees', 'Spelling Bees'), ('debate', 'Debate'), ('quiz', 'Quiz'), ('swimming', 'Swimming'), ('karate', 'Karate'), ('costumeday', 'Costume Day')], default='debate', max_length=92),
        ),
        migrations.AddField(
            model_name='school',
            name='admin',
            field=models.CharField(default='N/A', max_length=128),
        ),
        migrations.AddField(
            model_name='school',
            name='approval_number',
            field=models.CharField(default='Awaiting', max_length=11),
        ),
        migrations.AddField(
            model_name='school',
            name='approved_exams',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('ncce', 'National Common Entrance Examinations'), ('scce', 'State Common Entrance Examinatins'), ('waec', 'West African Examination Council Exams'), ('neco', 'National Examinations Council Exams'), ('jwaec', 'Junior West African Examination Council Exams'), ('jneco', 'Junior National Examinations Council Exams'), ('toefl', 'TOEFL Exams'), ('ielts', 'IELTS Exams'), ('alevel', 'A-Levels Exams'), ('igcse', 'IGCSE Exams')], default='ncce', max_length=56),
        ),
        migrations.AddField(
            model_name='school',
            name='boarding',
            field=models.CharField(choices=[('fb', 'Full Boarding'), ('fd', 'Day Only'), ('bd', 'Day and Boarding')], default='bd', max_length=2),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='clubs',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('bscout', 'Boys Scout'), ('gguide', 'Girls Guide'), ('frsc', 'FRSC Club'), ('music', 'Music Club'), ('drama', 'Drama Club'), ('debate', 'Debate Club'), ('press', 'Press Club'), ('jets', 'JETS Club'), ('rcross', 'Red Cross'), ('artscraft', 'Arts-Craft Club')], default='debate', max_length=65),
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(default='Nigeria', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.CharField(blank=True, default='No description yet...', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='facilities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sickbay', 'Sickbay'), ('multipurposehall', 'Multipurpose Hall'), ('sciencelab', 'Science Lab'), ('busservice', 'Bus Service'), ('library', 'Library'), ('playground', 'Playground'), ('sportscomplex', 'Sports Complex'), ('ictcenter', 'ICT Center'), ('artstudio', 'Art Studio'), ('elibrary', 'E-Library'), ('swimmingpool', 'Swimming Pool'), ('orchard', 'Orchard'), ('farmhouse', 'Farmhouse'), ('specialneeds', 'Special Needs Care'), ('musicstudio', 'Music Studio'), ('stem', 'STEM'), ('homemanagementlab', 'Home Management Lab'), ('languagestudio', 'Language Studio')], default='playground', max_length=202),
        ),
        migrations.AddField(
            model_name='school',
            name='gender',
            field=models.CharField(choices=[('m', 'Male Only'), ('f', 'Female Only'), ('mx', 'Mixed')], default='mx', max_length=2),
        ),
        migrations.AddField(
            model_name='school',
            name='lga',
            field=models.CharField(default='Ikeja', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, default='N/A', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('c', 'Creche'), ('n', 'Nursery'), ('p', 'Primary'), ('s', 'Secondary'), ('al', 'A-Levels')], default='n', max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(default='Lagos', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='street',
            field=models.CharField(default='11, Saka Tinubu Street', max_length=640),
        ),
        migrations.AddField(
            model_name='school',
            name='town',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
