# Generated by Django 2.1.7 on 2019-03-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20190327_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='aLevels',
            field=models.BooleanField(default=False, verbose_name='A-Levels'),
        ),
        migrations.AlterField(
            model_name='school',
            name='admin',
            field=models.CharField(default='N/A', max_length=128, verbose_name='Admission Officer'),
        ),
        migrations.AlterField(
            model_name='school',
            name='alevel',
            field=models.BooleanField(default=False, verbose_name='A-Levels Examinations'),
        ),
        migrations.AlterField(
            model_name='school',
            name='approval_number',
            field=models.CharField(default='Awaiting', max_length=11, verbose_name='Govt Approval Number'),
        ),
        migrations.AlterField(
            model_name='school',
            name='artscraft',
            field=models.BooleanField(default=False, verbose_name='Arts and Craft'),
        ),
        migrations.AlterField(
            model_name='school',
            name='artstudio',
            field=models.BooleanField(default=False, verbose_name='Art Studio'),
        ),
        migrations.AlterField(
            model_name='school',
            name='bscout',
            field=models.BooleanField(default=False, verbose_name="Boy's Scout"),
        ),
        migrations.AlterField(
            model_name='school',
            name='busservice',
            field=models.BooleanField(default=False, verbose_name='Bus Service'),
        ),
        migrations.AlterField(
            model_name='school',
            name='costumeday',
            field=models.BooleanField(default=False, verbose_name='Costume Day'),
        ),
        migrations.AlterField(
            model_name='school',
            name='culturalday',
            field=models.BooleanField(default=False, verbose_name='Cultural Day'),
        ),
        migrations.AlterField(
            model_name='school',
            name='elibrary',
            field=models.BooleanField(default=False, verbose_name='E-Library'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=128, verbose_name='School Email'),
        ),
        migrations.AlterField(
            model_name='school',
            name='farmhouse',
            field=models.BooleanField(default=False, verbose_name='Farm House'),
        ),
        migrations.AlterField(
            model_name='school',
            name='frsc',
            field=models.BooleanField(default=False, verbose_name='FRSC'),
        ),
        migrations.AlterField(
            model_name='school',
            name='gguide',
            field=models.BooleanField(default=False, verbose_name="Girl's Guide"),
        ),
        migrations.AlterField(
            model_name='school',
            name='homemanagementlab',
            field=models.BooleanField(default=False, verbose_name='Home Management Labs'),
        ),
        migrations.AlterField(
            model_name='school',
            name='ictcenter',
            field=models.BooleanField(default=False, verbose_name='ICT Center'),
        ),
        migrations.AlterField(
            model_name='school',
            name='ielts',
            field=models.BooleanField(default=False, verbose_name='IELTS Examinations'),
        ),
        migrations.AlterField(
            model_name='school',
            name='igcse',
            field=models.BooleanField(default=False, verbose_name='IGCSE Examinations'),
        ),
        migrations.AlterField(
            model_name='school',
            name='interhousesports',
            field=models.BooleanField(default=False, verbose_name='Inter House Sports'),
        ),
        migrations.AlterField(
            model_name='school',
            name='jneco',
            field=models.BooleanField(default=False, verbose_name='Junior National Examination Council Exams'),
        ),
        migrations.AlterField(
            model_name='school',
            name='jwaec',
            field=models.BooleanField(default=False, verbose_name='Junior West African Examination Council Exams'),
        ),
        migrations.AlterField(
            model_name='school',
            name='languagestudio',
            field=models.BooleanField(default=False, verbose_name='Languages Studio'),
        ),
        migrations.AlterField(
            model_name='school',
            name='multipurposehall',
            field=models.BooleanField(default=False, verbose_name='Multipurpose Hall'),
        ),
        migrations.AlterField(
            model_name='school',
            name='musicstudio',
            field=models.BooleanField(default=False, verbose_name='Music Studio'),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=128, verbose_name='School Name'),
        ),
        migrations.AlterField(
            model_name='school',
            name='ncce',
            field=models.BooleanField(default=False, verbose_name='National Common Entrance Examinations'),
        ),
        migrations.AlterField(
            model_name='school',
            name='neco',
            field=models.BooleanField(default=False, verbose_name='Senior National Examination Council Exams'),
        ),
        migrations.AlterField(
            model_name='school',
            name='orchard',
            field=models.BooleanField(default=False, verbose_name='Orchard'),
        ),
        migrations.AlterField(
            model_name='school',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='School Phone'),
        ),
        migrations.AlterField(
            model_name='school',
            name='rcross',
            field=models.BooleanField(default=False, verbose_name='Red Cross'),
        ),
        migrations.AlterField(
            model_name='school',
            name='scce',
            field=models.BooleanField(default=False, verbose_name='State Common Entrance Examinations'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sciencelab',
            field=models.BooleanField(default=False, verbose_name='Science Lab'),
        ),
        migrations.AlterField(
            model_name='school',
            name='specialneeds',
            field=models.BooleanField(default=False, verbose_name='Special Needs Care'),
        ),
        migrations.AlterField(
            model_name='school',
            name='spellingbees',
            field=models.BooleanField(default=False, verbose_name='Spelling Bees'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sportscomplex',
            field=models.BooleanField(default=False, verbose_name='Sports Complex'),
        ),
        migrations.AlterField(
            model_name='school',
            name='stem',
            field=models.BooleanField(default=False, verbose_name='STEM Labs'),
        ),
        migrations.AlterField(
            model_name='school',
            name='toefl',
            field=models.BooleanField(default=False, verbose_name='TOEFL Examinations'),
        ),
        migrations.AlterField(
            model_name='school',
            name='waec',
            field=models.BooleanField(default=False, verbose_name='Senior West African Examination Council Exams'),
        ),
    ]
