# Generated by Django 2.1.7 on 2019-04-08 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.ImageField(blank=True, upload_to='schools/'),
        ),
    ]
