# Generated by Django 2.1.7 on 2019-03-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20190327_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='lga',
            field=models.CharField(default='Ikeja', max_length=50, verbose_name='LGA'),
        ),
    ]
