# Generated by Django 2.1.7 on 2019-04-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20190409_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, upload_to='schools/logo/'),
        ),
    ]
