# Generated by Django 2.1.7 on 2019-04-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20190409_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
