# Generated by Django 2.1.7 on 2019-03-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20190327_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='jneco',
            field=models.BooleanField(default=False, verbose_name='Junior NECO Exams'),
        ),
        migrations.AlterField(
            model_name='school',
            name='jwaec',
            field=models.BooleanField(default=False, verbose_name='Junior WAEC Exams'),
        ),
        migrations.AlterField(
            model_name='school',
            name='neco',
            field=models.BooleanField(default=False, verbose_name='Senior NECO Exams'),
        ),
        migrations.AlterField(
            model_name='school',
            name='waec',
            field=models.BooleanField(default=False, verbose_name='Senior WAEC Exams'),
        ),
    ]
