# Generated by Django 2.1.7 on 2019-03-27 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20190327_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='ncce',
            field=models.BooleanField(default=False, verbose_name='National Common Entrance Exams'),
        ),
        migrations.AlterField(
            model_name='school',
            name='scce',
            field=models.BooleanField(default=False, verbose_name='State Common Entrance Exams'),
        ),
    ]
