# Generated by Django 2.1.7 on 2019-03-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20190327_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='alevel',
            field=models.BooleanField(default=False, verbose_name='A-Levels Exams'),
        ),
        migrations.AlterField(
            model_name='school',
            name='ielts',
            field=models.BooleanField(default=False, verbose_name='IELTS Exams'),
        ),
        migrations.AlterField(
            model_name='school',
            name='igcse',
            field=models.BooleanField(default=False, verbose_name='IGCSE Exams'),
        ),
        migrations.AlterField(
            model_name='school',
            name='ncce',
            field=models.BooleanField(default=False, verbose_name='National Common Entrance'),
        ),
        migrations.AlterField(
            model_name='school',
            name='scce',
            field=models.BooleanField(default=False, verbose_name='State Common Entrance'),
        ),
        migrations.AlterField(
            model_name='school',
            name='toefl',
            field=models.BooleanField(default=False, verbose_name='TOEFL Exams'),
        ),
    ]
