# Generated by Django 2.1.7 on 2019-03-27 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20190327_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='elibrary',
        ),
        migrations.RemoveField(
            model_name='school',
            name='stem',
        ),
        migrations.AlterField(
            model_name='school',
            name='jets',
            field=models.BooleanField(default=False, verbose_name='JETs'),
        ),
        migrations.AlterField(
            model_name='school',
            name='nursery',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
