# Generated by Django 2.1.7 on 2019-06-19 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_auto_20190617_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='ncce',
            new_name='ncee',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='scce',
            new_name='scee',
        ),
    ]
