# Generated by Django 2.1.7 on 2019-06-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_auto_20190619_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='carol',
            field=models.BooleanField(default=False, verbose_name='Carol'),
        ),
        migrations.AlterField(
            model_name='school',
            name='creche',
            field=models.BooleanField(default=False, verbose_name='Creche'),
        ),
        migrations.AlterField(
            model_name='school',
            name='dance',
            field=models.BooleanField(default=False, verbose_name='Dance'),
        ),
        migrations.AlterField(
            model_name='school',
            name='debate',
            field=models.BooleanField(default=False, verbose_name='Debate'),
        ),
        migrations.AlterField(
            model_name='school',
            name='drama',
            field=models.BooleanField(default=False, verbose_name='Drama'),
        ),
        migrations.AlterField(
            model_name='school',
            name='karate',
            field=models.BooleanField(default=False, verbose_name='Karate'),
        ),
        migrations.AlterField(
            model_name='school',
            name='library',
            field=models.BooleanField(default=False, verbose_name='Library'),
        ),
        migrations.AlterField(
            model_name='school',
            name='music',
            field=models.BooleanField(default=False, verbose_name='Music'),
        ),
        migrations.AlterField(
            model_name='school',
            name='nursery',
            field=models.BooleanField(default=False, verbose_name='Nursery'),
        ),
        migrations.AlterField(
            model_name='school',
            name='press',
            field=models.BooleanField(default=False, verbose_name='Press'),
        ),
        migrations.AlterField(
            model_name='school',
            name='primary',
            field=models.BooleanField(default=False, verbose_name='Primary'),
        ),
        migrations.AlterField(
            model_name='school',
            name='quiz',
            field=models.BooleanField(default=False, verbose_name='Quiz'),
        ),
        migrations.AlterField(
            model_name='school',
            name='secondary',
            field=models.BooleanField(default=False, verbose_name='Secondary'),
        ),
        migrations.AlterField(
            model_name='school',
            name='sickbay',
            field=models.BooleanField(default=False, verbose_name='Sickbay'),
        ),
        migrations.AlterField(
            model_name='school',
            name='swimming',
            field=models.BooleanField(default=False, verbose_name='Swimming'),
        ),
        migrations.AlterField(
            model_name='school',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
