# Generated by Django 2.1.5 on 2019-01-20 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('institution_one', models.CharField(blank=True, max_length=100, null=True)),
                ('course_one', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification_one', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date_one', models.DateField(blank=True, null=True)),
                ('end_date_one', models.DateField(blank=True, null=True)),
                ('awards_one', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('organization_one', models.CharField(blank=True, max_length=100, null=True)),
                ('job_position_one', models.CharField(blank=True, max_length=100, null=True)),
                ('location_one', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date_one', models.DateField(blank=True, null=True)),
                ('end_date_one', models.DateField(blank=True, null=True)),
                ('reponsibility_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('awards_one', models.CharField(blank=True, max_length=1000, null=True)),
                ('specialization_one', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('phone_num', models.IntegerField()),
                ('years_of_experience', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Tutor'),
        ),
        migrations.AddField(
            model_name='education',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.Tutor'),
        ),
    ]
