# Generated by Django 2.1.5 on 2019-01-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20190121_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='username',
            field=models.CharField(default='first_name + last_name', max_length=50, unique=True),
        ),
    ]
