# Generated by Django 2.1.5 on 2019-01-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_tutor_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
