# Generated by Django 2.1.5 on 2019-01-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_auto_20190121_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='phone_num',
            field=models.CharField(max_length=15),
        ),
    ]
