# Generated by Django 2.1.5 on 2019-01-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_auto_20190121_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='awards_one',
            new_name='awards',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='course_one',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='end_date_one',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='institution_one',
            new_name='institution',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='qualification_one',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='start_date_one',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='awards_one',
            new_name='awards',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='end_date_one',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='job_position_one',
            new_name='job_position',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='location_one',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='organization_one',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='reponsibility_one',
            new_name='reponsibility',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='specialization_one',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='start_date_one',
            new_name='start_date',
        ),
    ]
