# Generated by Django 2.1.5 on 2019-02-19 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='approval_number',
            field=models.CharField(default='Awaiting', max_length=11),
        ),
        migrations.AddField(
            model_name='school',
            name='approved_exams',
            field=models.CharField(default='NCEE', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='contact_person',
            field=models.CharField(default='Not Available', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='founded_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_type',
            field=models.CharField(default='Nursery', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='telephone',
            field=models.CharField(blank=True, default='+2349090587701', max_length=17),
        ),
        migrations.AlterField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
