# Generated by Django 2.1.5 on 2019-02-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_auto_20190219_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='contact_person',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.CharField(blank=True, default='N/A', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='lga',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, default='N/A', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='slug',
            field=models.SlugField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(blank=True, default='Lagos', max_length=100, null=True),
        ),
    ]
