# Generated by Django 2.1.5 on 2019-02-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_auto_20190220_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='founded_date',
        ),
    ]
