# Generated by Django 2.1.5 on 2019-02-20 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_remove_school_founded_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='founded_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
