# Generated by Django 2.1.5 on 2019-02-20 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_school_founded_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='founded_date',
        ),
    ]
